config/routes.rb
Rails.application.routes.draw do
  
root 'baseball_stadiums#index'

get "stadiums/" => "baseball_stadiums#index"
get "stadiums/new" => "baseball_stadiums#new", as: :baseball_stadia

get "stadiums/:id" => "baseball_stadiums#show", as: :stadium

post "stadiums/:id/reviews/" => "reviews#create", as: :reviews
get "stadiums/:id/reviews/new" => "reviews#new", as: :new_stadium_review
get "stadiums/:id/reviews/edit" => "reviews#edit", as: :edit_stadium_review
get "stadiums/:id/reviews/show" => "reviews#show", as: :stadium_review

  

end

app/models/baseball_stadium.rb
class BaseballStadium < ActiveRecord::Base
	has_many :reviews
	has_many :user, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :baseball_stadium
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :baseball_stadiums, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baseball_stadiums_controller.rb
class BaseballStadiumsController < ApplicationController

	def index
		@stadium = BaseballStadium.all
	end

	def show
		@stadium = BaseballStadium.find(params[:id])

	end

	def new
		@stadium = BaseballStadium.new
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	# def index
	# 	@review = Review.all
	# end
	
	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		if @review.save
			redirect_to stadiums_path
		else
			render :new
		end
	end

	def edit
		@review = Review.find(params[:id]) 
    end

end

private
    def review_params
        params.require(:review).permit(:comment, :rating)
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
			redirect_to users_path
	end

	def update
	end
end

private
    def user_params
        params.require(:user).permit(:name, :email)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baseball_stadiums_helper.rb
module BaseballStadiumsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baseball_stadiums/index.html.erb
<h1>Take Me Out To The Ballgame! </h1>


	<ul>
		
	<% @stadium.each do |s| %>
		<li>
		<%= s.name %>
		<%= link_to "Visit Stadium", stadium_path(s) %>
		</li>
	<% end %>

	</ul>


	

app/views/baseball_stadiums/new.html.erb
<h1>Add a new Stadium </h1>

<%= form_for @stadium do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :team %>
		<%= f.text_field :team %>
	</div>

	<div>
		<%= f.label :league %>
		<%= f.text_field :league %>
	</div>

	<div>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>

	<%= f.submit "Add a new Stadium!" %>

<% end %>

<%= link_to "Back to list", stadiums_path %>

app/views/baseball_stadiums/show.html.erb
<h1> <%= @stadium.name %> </h1> 


<p> This stadium is the home of the <%= @stadium.team %>, it is in the <%= @stadium.league %>, it is located at <%= @stadium.address %>
</p>

<%= link_to "Back to index", stadiums_path %>

<%= link_to "Submit a Review", new_stadium_review_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaseballStadiumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>

	<div class="field">
		<%= f.label :comment %><br>
		<%= f.text_area :comment, size: "50x10" %><br>
		</div>

	 	<div class="rating">
	    <%= f.label :rating %><br>
	    <%= f.text_field :rating %>
	    </div>
		
		<div class="actions">
		<%= f.submit %>	
	</div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit a comment!</h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>Leave a Stadium Review here!</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<h1>Show a comment</h1>

<%= render 'form' %>